# -*- coding: utf-8 -*-
"""Demographic_snapshot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7K09RHAwUw4OoblY6rK4_7OunehBwFj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive 
drive.mount('/content/gdrive')

snapshot_one = pd.read_csv("gdrive/My Drive/2013_-_2018_Demographic_Snapshot_School.csv")
snapshot_one

snapshot_one = snapshot_one.drop(columns=['Grade K', 'Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', '# White', '# Students with Disabilities', 'Grade 5', 'Grade 9', '# Multiple Race Categories Not Represented', '# English Language Learners', '# Poverty', '# Black', 'Grade PK (Half Day & Full Day)','Grade 10', 'Grade 11', '# Female', '# Male', "Grade 12",'# Asian', '# Hispanic','Economic Need Index'])

for col in snapshot_one.columns:
    print(col)

snapshot_one.DBN.value_counts()

middle_school = pd.read_csv("gdrive/My Drive/2018_DOE_Middle_School_Directory.csv")
print(middle_school.columns)

middle_school.rename(columns = {'schooldbn':'DBN'}, inplace = True)
middle_school

merged_df = pd.merge(snapshot_one, middle_school, on="DBN")
merged_df = merged_df.drop(merged_df.iloc[:, 17:],axis = 1)
merged_df

print(merged_df.columns)

"""Index(['DBN', 'School Name', 'Year', 'Total Enrollment', 'Grade 6', 'Grade 7',
       'Grade 8', '% Female', '% Male', '% Asian', '% Black', '% Hispanic',
       '% Multi-Racial', '% Native American', '% White',
       '% Missing Race/Ethnicity Data', '% Students with Disabilities',
       '% English Language Learners', '% Poverty'],
      dtype='object')
"""

snapshot_two = pd.read_csv("gdrive/My Drive/2017-18__-_2021-22_Demographic_Snapshot.csv")
snapshot_two

snapshot_two['% Poverty'] = snapshot_two['% Poverty'] .str.replace('%','').str.replace('Above', '')
snapshot_two.head(20)

snapshot_two = snapshot_two.drop(columns=['Grade 3K','# Missing Race/Ethnicity Data','Grade K','# Multi-Racial','# Native American','Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', '# White', '# Students with Disabilities', 'Grade 5', 'Grade 9', '# English Language Learners', '# Poverty', '# Black', 'Grade PK (Half Day & Full Day)','Grade 10', 'Grade 11', '# Female', '# Male', "Grade 12",'# Asian', '# Hispanic','Economic Need Index'])

print(snapshot_two.columns)



demographic_snapshot= pd.concat([merged_df, snapshot_two],                  
                      ignore_index = True,
                      sort = False)
demographic_snapshot = demographic_snapshot.drop(columns=["Total Enrollment", "% Multi-Racial", "% Native American", "% Missing Race/Ethnicity Data"])
demographic_snapshot= demographic_snapshot.rename(columns={'DBN': 'School_DBN', 'School Name': 'School_Name', 'Grade 6':'Grade_6', 'Grade 7':'Grade_7', 'Grade 8':'Grade_8', ' % Multiple Race Categories Not Represented': '% Multiple_Race_Categories_Not_Represented', })
demographic_snapshot = demographic_snapshot.fillna(0)
demographic_snapshot = demographic_snapshot.round(2)
demographic_snapshot['% Poverty'] = demographic_snapshot['% Poverty'].astype(float)
demographic_snapshot

demographic_snapshot.info()

demographic_snapshot.size

